# Generated by Django 5.2.5 on 2025-08-28 10:18

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLocation',
            fields=[
            ],
            options={
                'verbose_name': 'Master Location',
                'verbose_name_plural': 'Master Locations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hotel_app.location',),
        ),
        migrations.CreateModel(
            name='MasterUser',
            fields=[
            ],
            options={
                'verbose_name': 'Master User',
                'verbose_name_plural': 'Master Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
