# Generated by Django 5.2.5 on 2025-08-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_complaint_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
