# Generated by Django 5.2.5 on 2025-09-03 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfastvoucher',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='breakfastvoucher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='breakfastvoucher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='breakfastvoucher',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='breakfastvoucher',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='breakfastvoucher',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/'),
        ),
        migrations.AddField(
            model_name='breakfastvoucher',
            name='redeemed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakfastvoucher',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakfastvoucher',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='breakfast_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='breakfastvoucher',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='breakfastvoucher',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestcomment',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gymvisitor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationfamily',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='requestfamily',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workfamily',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='step_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('building', 'floor_number')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('building', 'room_no')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_order')},
        ),
    ]
