# Generated by Django 5.2.5 on 2025-09-04 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_remove_breakfastvoucher_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('voucher_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='breakfastvoucherscan',
            name='scanned_by_user',
        ),
        migrations.AddField(
            model_name='breakfastvoucherscan',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='breakfastvoucherscan',
            name='source',
            field=models.CharField(default='web', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfastvoucherscan',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='hotel_app.breakfastvoucher'),
        ),
    ]
