# Generated by Django 5.2.5 on 2025-09-04 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_voucher_remove_breakfastvoucherscan_scanned_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
