# Generated by Django 5.2.5 on 2025-09-04 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_voucher_created_at_voucher_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan_result', models.CharField(choices=[('success', 'Successful Redemption'), ('already_redeemed', 'Already Redeemed'), ('expired', 'Expired'), ('invalid', 'Invalid Voucher'), ('wrong_date', 'Wrong Date'), ('error', 'System Error')], max_length=20)),
                ('redemption_successful', models.BooleanField(default=False)),
                ('scan_source', models.CharField(default='web', max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='breakfastvoucher',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legacy Breakfast Voucher', 'verbose_name_plural': 'Legacy Breakfast Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='breakfastvoucherscan',
            options={'ordering': ['-scanned_at'], 'verbose_name': 'Legacy Breakfast Voucher Scan', 'verbose_name_plural': 'Legacy Breakfast Voucher Scans'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='package_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='hotel_app.guest'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.location'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='qr_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/qr/'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='sent_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='voucher',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast Voucher'), ('spa', 'Spa Voucher'), ('gym', 'Gym Voucher'), ('pool', 'Pool Access'), ('general', 'General Service')], default='breakfast', max_length=20),
        ),
        migrations.AddField(
            model_name='voucher',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breakfastvoucher',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='breakfastvoucher',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='breakfastvoucherscan',
            name='scanned_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='breakfastvoucherscan',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_voucher_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='breakfastvoucherscan',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_scans', to='hotel_app.breakfastvoucher'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='guestcomment',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.guest'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.guest'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['guest_id'], name='hotel_app_g_guest_i_cfb667_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['room_number'], name='hotel_app_g_room_nu_f059bc_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['checkin_date', 'checkout_date'], name='hotel_app_g_checkin_8a4ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_code'], name='hotel_app_v_voucher_4d5128_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status'], name='hotel_app_v_status_70573c_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['guest'], name='hotel_app_v_guest_i_6b7c59_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['valid_from', 'valid_to'], name='hotel_app_v_valid_f_2dbcc8_idx'),
        ),
        migrations.AddField(
            model_name='voucherscan',
            name='scan_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.location'),
        ),
        migrations.AddField(
            model_name='voucherscan',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherscan',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='hotel_app.voucher'),
        ),
        migrations.AddIndex(
            model_name='voucherscan',
            index=models.Index(fields=['voucher', 'scanned_at'], name='hotel_app_v_voucher_7dab58_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherscan',
            index=models.Index(fields=['scanned_at'], name='hotel_app_v_scanned_2153b4_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherscan',
            index=models.Index(fields=['scan_result'], name='hotel_app_v_scan_re_4ee862_idx'),
        ),
    ]
