# Generated by Django 5.2.5 on 2025-09-06 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_voucherscan_alter_breakfastvoucher_options_and_more'),
    ]

    operations = [
    ]
