# Generated by Django 5.2.5 on 2025-09-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_auto_20250906_0803'),
        ('hotel_app', '0010_guest_datetime_fields'),
    ]

    operations = [
    ]
