# Generated by Django 5.2.5 on 2025-09-06 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0011_merge_20250906_0817'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guest',
            name='hotel_app_g_checkin_f8b9c1_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='hotel_app_b_booking_c56f5f_idx',
            old_name='hotel_app_b_booking_e2ac98_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='hotel_app_b_check_i_1839a6_idx',
            old_name='hotel_app_b_check_i_1c8b42_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='hotel_app_b_room_nu_68840a_idx',
            old_name='hotel_app_b_room_nu_6b4be8_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='hotel_app_v_check_i_9d26a6_idx',
            old_name='hotel_app_v_check_i_a9b7d3_idx',
        ),
        migrations.AlterField(
            model_name='breakfastvoucherscan',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('redeemed', 'Fully Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast Voucher'), ('gym', 'Gym Voucher'), ('spa', 'Spa Voucher'), ('restaurant', 'Restaurant Voucher')], default='breakfast', max_length=20),
        ),
    ]
