# Generated by Django 5.2.5 on 2025-09-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0012_remove_guest_hotel_app_g_checkin_f8b9c1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='details_qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='Guest Details QR Code (Base64)'),
        ),
    ]
