# Generated by Django 5.2.5 on 2025-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0013_change_qr_code_to_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='qr_image',
            field=models.TextField(blank=True, null=True, verbose_name='Voucher QR Code (Base64)'),
        ),
    ]
