# Generated by Django 5.2.5 on 2025-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0014_change_voucher_qr_to_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
