# Generated by Django 4.2.7 on 2025-09-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0016_complaint_assigned_to_complaint_due_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_groups', to='hotel_app.department'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
