# Generated by Django 4.2.7 on 2025-10-08 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.department'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='resolution_sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='response_sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='response_sla_hours',
            field=models.PositiveIntegerField(default=1, help_text='SLA time in hours to respond'),
        ),
    ]
