# Generated by Django 4.2.7 on 2025-10-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0023_slaconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True),
        ),
    ]
