# Generated by Django 4.2.7 on 2025-10-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0024_alter_servicerequest_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='response_sla_hours',
            field=models.FloatField(default=1, help_text='SLA time in hours to respond'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='sla_hours',
            field=models.FloatField(default=24, help_text='SLA time in hours to resolve'),
        ),
    ]
