# Generated by Django 4.2.7 on 2025-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0025_alter_servicerequest_response_sla_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Front Desk/Staff'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
