# Generated by Django 4.2.7 on 2025-10-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0026_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRequestSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], max_length=20)),
                ('response_time_minutes', models.PositiveIntegerField(help_text='Response time in minutes')),
                ('resolution_time_minutes', models.PositiveIntegerField(help_text='Resolution time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_configurations', to='hotel_app.department')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_configurations', to='hotel_app.requesttype')),
            ],
            options={
                'verbose_name': 'Department Request SLA',
                'verbose_name_plural': 'Department Request SLAs',
                'unique_together': {('department', 'request_type', 'priority')},
            },
        ),
    ]
